title: Solvahol Knowledge Base
description: A collection of concepts, how-to's, FAQs, and solutions related to Solvahol products and services
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->

gems:
  - jekyll-mentions

collections:
  concepts:
    output: true
  how-tos:
    output: true
  solutions:
    output: true

defaults:
  - scope:
      path: ""
      type: concepts
    values:
      layout: kb-article
  - scope:
      path: ""
      type: how-tos
    values:
      layout: kb-article
  - scope:
      path: ""
      type: solutions
    values:
      layout: kb-article
